-- Created a table and seed 100 Indian banks for seller profile bank dropdown
CREATE TABLE IF NOT EXISTS `indian_banks` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `bank_name` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_bank_name` (`bank_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `indian_banks` (`bank_name`) VALUES
('AU Small Finance Bank'),
('Abhyudaya Cooperative Bank'),
('Airtel Payments Bank'),
('Akola Janata Commercial Co-operative Bank'),
('Allahabad Bank'),
('Andhra Bank'),
('Apna Sahakari Bank'),
('Axis Bank'),
('Bandhan Bank'),
('Bank of America NA India'),
('Bank of Bahrain and Kuwait'),
('Bank of Baroda'),
('Bank of Ceylon'),
('Bank of India'),
('Bank of Maharashtra'),
('Barclays Bank India'),
('Bassein Catholic Cooperative Bank'),
('Bharat Cooperative Bank Mumbai'),
('BNP Paribas India'),
('Canara Bank'),
('Capital Small Finance Bank'),
('Catholic Syrian Bank'),
('Central Bank of India'),
('Chhattisgarh Rajya Gramin Bank'),
('Citi Bank'),
('City Union Bank'),
('Coastal Local Area Bank'),
('Corporation Bank'),
('Cosmos Cooperative Bank'),
('DCB Bank'),
('Deutsche Bank India'),
('Development Credit Bank'),
('Dhanalakshmi Bank'),
('Dombivli Nagari Sahakari Bank'),
('Durgapur Steel Peoples Cooperative Bank'),
('Equitas Small Finance Bank'),
('ESAF Small Finance Bank'),
('Federal Bank'),
('Fincare Small Finance Bank'),
('Fino Payments Bank'),
('Gopinath Patil Parsik Janata Sahakari Bank'),
('HDFC Bank'),
('HSBC India'),
('ICICI Bank'),
('IDBI Bank'),
('IDFC First Bank'),
('India Post Payments Bank'),
('Indian Bank'),
('Indian Overseas Bank'),
('IndusInd Bank'),
('Jammu and Kashmir Bank'),
('Jana Small Finance Bank'),
('Janakalyan Sahakari Bank'),
('Janaseva Sahakari Bank'),
('Janata Sahakari Bank Pune'),
('Kallappanna Awade Ichalkaranji Janata Sahakari Bank'),
('Kalupur Commercial Cooperative Bank'),
('Karnataka Bank'),
('Karnataka Gramin Bank'),
('Karur Vysya Bank'),
('Kerala Gramin Bank'),
('Kotak Mahindra Bank'),
('Maharashtra Gramin Bank'),
('Mahanagar Cooperative Bank'),
('Maharashtra State Cooperative Bank'),
('Mehsana Urban Cooperative Bank'),
('Model Co-operative Bank'),
('Nagpur Nagarik Sahakari Bank'),
('Nainital Bank'),
('NSDL Payments Bank'),
('Nutan Nagarik Sahakari Bank'),
('Paytm Payments Bank'),
('Punjab and Sind Bank'),
('Punjab National Bank'),
('Rajasthan Marudhara Gramin Bank'),
('RBL Bank'),
('Saraswat Cooperative Bank'),
('Sarva Haryana Gramin Bank'),
('Shamrao Vithal Cooperative Bank'),
('Shinhan Bank India'),
('Shivalik Small Finance Bank'),
('South Indian Bank'),
('Standard Chartered Bank India'),
('State Bank of India'),
('Suryoday Small Finance Bank'),
('Tamilnad Mercantile Bank'),
('Telangana Grameena Bank'),
('The Royal Bank of Scotland N V India'),
('Thane Bharat Sahakari Bank'),
('TJSB Sahakari Bank'),
('UCO Bank'),
('Ujjivan Small Finance Bank'),
('Union Bank of India'),
('United Bank of India'),
('Utkarsh Small Finance Bank'),
('Vasai Vikas Sahakari Bank'),
('West Bengal State Cooperative Bank'),
('Yadgir District Central Cooperative Bank'),
('Yes Bank'),
('Zoroastrian Cooperative Bank');
