<?php
defined('BASEPATH') or exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|
|	http://example.com/
|
| WARNING: You MUST set this value!
|
| If it is not set, then CodeIgniter will try guess the protocol and path
| your installation, but due to security concerns the hostname will be set
| to $_SERVER['SERVER_ADDR'] if available, or localhost otherwise.
| The auto-detection mechanism exists only for convenience during
| development and MUST NOT be used in production!
|
| If you need to allow multiple domains, remember that this file is still
| a PHP script and you can easily do that on your own.
|
*/

$config['base_url'] = APP_URL;

/*
|--------------------------------------------------------------------------
| Index File
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
|
*/
$config['index_page'] = '';

/*
|--------------------------------------------------------------------------
| URI PROTOCOL
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of 'REQUEST_URI' works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
|
| 'REQUEST_URI'    Uses $_SERVER['REQUEST_URI']
| 'QUERY_STRING'   Uses $_SERVER['QUERY_STRING']
| 'PATH_INFO'      Uses $_SERVER['PATH_INFO']
|
| WARNING: If you set this to 'PATH_INFO', URIs will always be URL-decoded!
*/
$config['uri_protocol']    = 'REQUEST_URI';

/*
|--------------------------------------------------------------------------
| URL suffix
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
| For more information please see the user guide:
|
| https://codeigniter.com/user_guide/general/urls.html
*/
$config['url_suffix'] = '';

/*
|--------------------------------------------------------------------------
| Default Language
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
|
*/
$config['language']    = 'english';

/*
|--------------------------------------------------------------------------
| Default Character Set
|--------------------------------------------------------------------------
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
|
| See http://php.net/htmlspecialchars for a list of supported charsets.
|
*/
$config['charset'] = 'UTF-8';

/*
|--------------------------------------------------------------------------
| Enable/Disable System Hooks
|--------------------------------------------------------------------------
|
| If you would like to use the 'hooks' feature you must enable it by
| setting this variable to TRUE (boolean).  See the user guide for details.
|
*/
$config['enable_hooks'] = TRUE;

/*
|--------------------------------------------------------------------------
| Class Extension Prefix
|--------------------------------------------------------------------------
|
| This item allows you to set the filename/classname prefix when extending
| native libraries.  For more information please see the user guide:
|
| https://codeigniter.com/user_guide/general/core_classes.html
| https://codeigniter.com/user_guide/general/creating_libraries.html
|
*/
$config['subclass_prefix'] = 'MY_';

/*
|--------------------------------------------------------------------------
| Composer auto-loading
|--------------------------------------------------------------------------
|
| Enabling this setting will tell CodeIgniter to look for a Composer
| package auto-loader script in application/vendor/autoload.php.
|
|	$config['composer_autoload'] = TRUE;
|
| Or if you have your vendor/ directory located somewhere else, you
| can opt to set a specific path as well:
|
|	$config['composer_autoload'] = '/path/to/vendor/autoload.php';
|
| For more information about Composer, please visit http://getcomposer.org/
|
| Note: This will NOT disable or override the CodeIgniter-specific
|	autoloading (application/config/autoload.php)
*/
$config['composer_autoload'] = FCPATH . 'vendor/autoload.php';

/*
|--------------------------------------------------------------------------
| Allowed URL Characters
|--------------------------------------------------------------------------
|
| This lets you specify which characters are permitted within your URLs.
| When someone tries to submit a URL with disallowed characters they will
| get a warning message.
|
| As a security measure you are STRONGLY encouraged to restrict URLs to
| as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
|
| Leave blank to allow all characters -- but only if you are insane.
|
| The configured value is actually a regular expression character group
| and it will be executed as: ! preg_match('/^[<permitted_uri_chars>]+$/i
|
| DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
|
*/

$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-@\=';

/*
|--------------------------------------------------------------------------
| Enable Query Strings
|--------------------------------------------------------------------------
|
| By default CodeIgniter uses search-engine friendly segment based URLs:
| example.com/who/what/where/
|
| You can optionally enable standard query string based URLs:
| example.com?who=me&what=something&where=here
|
| Options are: TRUE or FALSE (boolean)
|
| The other items let you set the query string 'words' that will
| invoke your controllers and its functions:
| example.com/index.php?c=controller&m=function
|
| Please note that some of the helpers won't work as expected when
| this feature is enabled, since CodeIgniter is designed primarily to
| use segment based URLs.
|
*/
$config['enable_query_strings'] = FALSE;
$config['controller_trigger'] = 'c';
$config['function_trigger'] = 'm';
$config['directory_trigger'] = 'd';

/*
|--------------------------------------------------------------------------
| Allow $_GET array
|--------------------------------------------------------------------------
|
| By default CodeIgniter enables access to the $_GET array.  If for some
| reason you would like to disable it, set 'allow_get_array' to FALSE.
|
| WARNING: This feature is DEPRECATED and currently available only
|          for backwards compatibility purposes!
|
*/
$config['allow_get_array'] = TRUE;


/*
|--------------------------------------------------------------------------
| Error Logging Threshold
|--------------------------------------------------------------------------
|
| You can enable error logging by setting a threshold over zero. The
| threshold determines what gets logged. Threshold options are:
|
|	0 = Disables logging, Error logging TURNED OFF
|	1 = Error Messages (including PHP errors)
|	2 = Debug Messages
|	3 = Informational Messages
|	4 = All Messages
|
| You can also pass an array with threshold levels to show individual error types
|
| 	array(2) = Debug Messages, without Error Messages
|
| For a live site you'll usually only enable Errors (1) to be logged otherwise
| your log files will fill up very fast.
|
*/
/*
 * Errors only (1), in every environment.
 *
 * This setting was previously assigned TWICE in this file - `= 4` about twenty
 * lines above, then `= 1` here. PHP keeps the last assignment, so the effective
 * value has always been 1; the stray `= 4` was dead, and misleading enough that it
 * read like the application was logging every message on every request. It has been
 * removed and this, the assignment that was always in force, is left in place.
 *
 * Threshold 4 writes an entry for every debug and informational message, which on a
 * page issuing hundreds of statements means a synchronous file write per message.
 * Keep this at 1 in production.
 */
$config['log_threshold'] = 1;

/*
|--------------------------------------------------------------------------
| Error Logging Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/logs/ directory. Use a full server path with trailing slash.
|
*/
$config['log_path'] = '';

/*
|--------------------------------------------------------------------------
| Log File Extension
|--------------------------------------------------------------------------
|
| The default filename extension for log files. The default 'php' allows for
| protecting the log files via basic scripting, when they are to be stored
| under a publicly accessible directory.
|
| Note: Leaving it blank will default to 'php'.
|
*/
$config['log_file_extension'] = '';

/*
|--------------------------------------------------------------------------
| Log File Permissions
|--------------------------------------------------------------------------
|
| The file system permissions to be applied on newly created log files.
|
| IMPORTANT: This MUST be an integer (no quotes) and you MUST use octal
|            integer notation (i.e. 0700, 0644, etc.)
*/
$config['log_file_permissions'] = 0644;

/*
|--------------------------------------------------------------------------
| Date Format for Logs
|--------------------------------------------------------------------------
|
| Each item that is logged has an associated date. You can use PHP date
| codes to set your own date formatting
|
*/
$config['log_date_format'] = 'Y-m-d H:i:s';

/*
|--------------------------------------------------------------------------
| Error Views Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/views/errors/ directory.  Use a full server path with trailing slash.
|
*/
$config['error_views_path'] = '';

/*
|--------------------------------------------------------------------------
| Cache Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/cache/ directory.  Use a full server path with trailing slash.
|
*/
$config['cache_path'] = 'cache/';

/*
|--------------------------------------------------------------------------
| Cache Include Query String
|--------------------------------------------------------------------------
|
| Whether to take the URL query string into consideration when generating
| output cache files. Valid options are:
|
|	FALSE      = Disabled
|	TRUE       = Enabled, take all query parameters into account.
|	             Please be aware that this may result in numerous cache
|	             files generated for the same page over and over again.
|	array('q') = Enabled, but only take into account the specified list
|	             of query parameters.
|
*/
$config['cache_query_string'] = FALSE;

/*
|--------------------------------------------------------------------------
| Encryption Key
|--------------------------------------------------------------------------
|
| If you use the Encryption class, you must set an encryption key.
| See the user guide for more info.
|
| https://codeigniter.com/user_guide/libraries/encryption.html
|
*/
/*
| Was '' - an EMPTY encryption key.
|
| Nothing in this application currently uses the Encryption library or encrypted
| cookies, so an empty key was inert rather than actively broken. But it is a loaded
| gun: the first feature that reaches for $this->encryption->encode() would encrypt
| with a key everybody knows, and it would do so silently, producing ciphertext that
| looks fine and protects nothing.
|
| Read from the environment, with no fallback, so the failure is loud instead: CI
| throws if the library is used without a key. Set it on the server alongside the
| other secrets:
|
|     SetEnv CI_ENCRYPTION_KEY "<32 random bytes, hex>"
|     php -r "echo bin2hex(random_bytes(32));"
|
| Note this file is tracked in git, which is exactly why the value is not written
| here - see the equivalent notes in config/constants.php and config/cron.php.
*/
$config['encryption_key'] = getenv('CI_ENCRYPTION_KEY') ?: '';

/*
|--------------------------------------------------------------------------
| Session Variables
|--------------------------------------------------------------------------
|
| 'sess_driver'
|
|	The storage driver to use: files, database, redis, memcached
|
| 'sess_cookie_name'
|
|	The session cookie name, must contain only [0-9a-z_-] characters
|
| 'sess_expiration'
|
|	The number of SECONDS you want the session to last.
|	Setting to 0 (zero) means expire when the browser is closed.
|
| 'sess_save_path'
|
|	The location to save sessions to, driver dependent.
|
|	For the 'files' driver, it's a path to a writable directory.
|	WARNING: Only absolute paths are supported!
|
|	For the 'database' driver, it's a table name.
|	Please read up the manual for the format with other session drivers.
|
|	IMPORTANT: You are REQUIRED to set a valid save path!
|
| 'sess_match_ip'
|
|	Whether to match the user's IP address when reading the session data.
|
|	WARNING: If you're using the database driver, don't forget to update
|	         your session table's PRIMARY KEY when changing this setting.
|
| 'sess_time_to_update'
|
|	How many seconds between CI regenerating the session ID.
|
| 'sess_regenerate_destroy'
|
|	Whether to destroy session data associated with the old session ID
|	when auto-regenerating the session ID. When set to FALSE, the data
|	will be later deleted by the garbage collector.
|
| Other session cookie settings are shared with the rest of the application,
| except for 'cookie_prefix' and 'cookie_httponly', which are ignored here.
|
*/
$config['sess_driver'] = 'files';
$config['sess_cookie_name'] = 'ci_session';
$config['sess_expiration'] = 7200;
/*
| SESSION STORAGE - was sys_get_temp_dir().
|
| On shared hosting that is a directory shared with every other account on the
| machine, and a session file is not a hash of a session - it IS the session. Anything
| that can read the file can resume the session it belongs to, admin sessions
| included. It is also where a co-tenant's own PHP process looks first.
|
| Moved inside the application, which is not web-reachable: application/.htaccess
| denies the directory outright and the root .htaccess blocks ^application/ as well.
| The directory ships with the repo (so the deploy creates it) and its contents are
| gitignored (so a live session id is never committed).
|
| NOTE ON DEPLOY: changing this path invalidates every existing session, so everyone -
| customers, sellers, admins - is signed out once, at the moment this goes live. That
| is a one-off, and it is the correct direction: the sessions being discarded are the
| ones that were stored somewhere readable.
|
| If the directory is not writable the file driver falls back to failing loudly rather
| than silently storing nothing, which is what you want to find out immediately.
*/
$config['sess_save_path'] = APPPATH . 'cache/sessions';

/*
| Left FALSE deliberately, and worth recording why rather than leaving it looking
| unconsidered. Binding a session to an IP would make a stolen cookie harder to reuse,
| but this site sits behind a CDN and serves a lot of mobile traffic: the client IP
| changes mid-session on any network handover, and every one of those would be a
| forced logout in the middle of a checkout. The protections that do the work here are
| the HttpOnly + Secure + SameSite cookie flags and sess_regenerate_destroy below.
*/
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 300;
// Destroy the old session file when the ID is regenerated. With this FALSE, every
// abandoned session ID stayed valid on disk until GC - including the pre-login ID that
// ion_auth regenerates away from at login, which is exactly the ID a session-fixation
// attempt plants. Regenerating without destroying leaves that planted ID working.
$config['sess_regenerate_destroy'] = TRUE;

/*
|--------------------------------------------------------------------------
| Cookie Related Variables
|--------------------------------------------------------------------------
|
| 'cookie_prefix'   = Set a cookie name prefix if you need to avoid collisions
| 'cookie_domain'   = Set to .your-domain.com for site-wide cookies
| 'cookie_path'     = Typically will be a forward slash
| 'cookie_secure'   = Cookie will only be set if a secure HTTPS connection exists.
| 'cookie_httponly' = Cookie will only be accessible via HTTP(S) (no javascript)
|
| Note: These settings (with the exception of 'cookie_prefix' and
|       'cookie_httponly') will also affect sessions.
|
*/
$config['cookie_prefix']    = '';
$config['cookie_domain']    = '';
$config['cookie_path']        = '/';
// Set only when the request actually arrived over HTTPS, so the session cookie is not
// leaked over plain HTTP on the live site, while local/HTTP development still logs in.
// Hardcoding TRUE would lock logins out of any non-HTTPS environment; hardcoding FALSE
// (the previous value) meant the live site's admin/seller session cookie had no Secure
// flag at all.
$config['cookie_secure']    = (
    (!empty($_SERVER['HTTPS']) && strtolower($_SERVER['HTTPS']) !== 'off')
    || (!empty($_SERVER['HTTP_X_FORWARDED_PROTO']) && strtolower($_SERVER['HTTP_X_FORWARDED_PROTO']) === 'https')
);
// Session cookie must not be readable from JavaScript - this is what stops any single
// stored-XSS on the storefront from being escalated into a stolen admin/seller session.
$config['cookie_httponly']     = TRUE;

/*
|--------------------------------------------------------------------------
| Standardize newlines
|--------------------------------------------------------------------------
|
| Determines whether to standardize newline characters in input data,
| meaning to replace \r\n, \r, \n occurrences with the PHP_EOL value.
|
| WARNING: This feature is DEPRECATED and currently available only
|          for backwards compatibility purposes!
|
*/
$config['standardize_newlines'] = FALSE;

/*
|--------------------------------------------------------------------------
| Global XSS Filtering
|--------------------------------------------------------------------------
|
| Determines whether the XSS filter is always active when GET, POST or
| COOKIE data is encountered
|
| WARNING: This feature is DEPRECATED and currently available only
|          for backwards compatibility purposes!
|
*/
$config['global_xss_filtering'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cross Site Request Forgery
|--------------------------------------------------------------------------
| Enables a CSRF cookie token to be set. When set to TRUE, token will be
| checked on a submitted form. If you are accepting user data, it is strongly
| recommended CSRF protection be enabled.
|
| 'csrf_token_name' = The token name
| 'csrf_cookie_name' = The cookie name
| 'csrf_expire' = The number in seconds the token should expire.
| 'csrf_regenerate' = Regenerate token on every submission
| 'csrf_exclude_uris' = Array of URIs which ignore CSRF checks
*/

// Was FALSE, so every state-changing POST in the app - admin settings, product and order
// edits, seller subscription purchases, password changes - could be triggered by any other
// site the victim happened to visit while logged in. assets/csrf-guard.js (loaded from
// every layout head) stamps the token onto raw <form> posts, $.ajax, FormData uploads,
// fetch and bare XHR, so turning this on does not require rewriting the ~36 hand-rolled
// forms and dozens of AJAX call sites that never used form_open().
$config['csrf_protection'] = TRUE;
$config['csrf_token_name'] = 'ekart_security_token';
$config['csrf_cookie_name'] = 'ekart_security_cookie';
$config['csrf_expire'] = 7200;
// Deliberately FALSE. Rotating the token on every single request breaks any page that
// fires two POSTs concurrently (the loser submits a token that was already spent), breaks
// the back button, and breaks a second browser tab - all of which this app does routinely
// via bootstrap-table refreshes and modal forms. A stable per-session token still blocks
// cross-site forgery, which is the entire point of the check.
$config['csrf_regenerate'] = FALSE;
/*
| CSRF EXEMPTIONS - now only endpoints that CANNOT carry our token.
|
| This list had grown to 22 entries and included the most destructive endpoints in
| the application. Anything on it accepts a cross-site POST, which means any page an
| authenticated admin happens to open can fire it. The worst entry was
| `admin/updater/upload_update_file`, which extracts an uploaded ZIP and copies files
| anywhere under the application root - i.e. an admin merely VISITING a malicious page
| was remote code execution, with no credential theft and no XSS required. Order
| deletion, product deletion, order status updates and category creation were all
| exempt too.
|
| Every removed entry was checked against its actual caller first, because a wrong
| removal here breaks the panel or the checkout rather than failing safe:
|
|   admin/updater/upload_update_file  form.form-submit-event -> custom.js appends the
|                                     token (see the FormData handler in custom.js)
|   admin/category/add_category       same form-submit-event handler
|   admin/product/process_bulk_upload #bulk_upload_form handler appends it explicitly
|   cart/place-order                  checkout.js place_order() appends it to FormData
|   cart/pre-payment-setup            checkout.js $.post sends [csrfName]: csrfHash
|   cart/validate-promo-code          cart.js + checkout.js both append it
|   my-account/get-address            checkout.js sends it in the POST data
|   admin/product/get_subcategory     GET
|   admin/orders/update_orders        GET
|   admin/orders/delete_orders        GET
|   admin/product/delete_product      GET
|   admin/product/update_product_order GET
|   admin/home/fetch_sales            GET (read-only)
|
| NOTE on the GET ones: CodeIgniter's CSRF check only applies to POST, so taking them
| off this list does not protect them - it just stops the list from implying they were
| considered. Destructive actions reached by GET are CSRF-able by construction, and
| the correct fix is to make them POST. delete_orders, delete_product and
| update_product_order have been converted; the rest are read-only.
|
| WHAT STAYS, and why each one genuinely cannot present a token:
|
|   admin/webhook/*        Payment gateway servers. They authenticate by HMAC
|                          signature instead - see the handlers in admin/Webhook.php,
|                          all of which verify one now.
|   payment/*              Gateway return and callback URLs; the browser arrives here
|                          from the provider's domain, so no token of ours exists.
|   app/v1/api/*           The mobile APIs. Token-authenticated (JWT in a header) and
|   seller/app/v1/api/*    cookie-less, so CSRF does not apply: there is no ambient
|   admin/app/v1/api/*     credential for a third-party site to ride on.
|   delivery_boy/app/v1/api/*
|   app/v1/chat_api/*
|   seller/app/v1/chat_api/*
|   admin/media/upload     TinyMCE's own uploader (images_upload_url) issues this
|                          request internally and has no way to attach our token. Left
|                          exempt deliberately: the endpoint is admin-gated and the
|                          allowed types exclude every executable extension, so the
|                          worst a forced call achieves is an unwanted image in the
|                          media library. Revisit if TinyMCE is ever reconfigured to
|                          use images_upload_handler, which can send the token.
*/
$config['csrf_exclude_uris'] = array(
    'admin/webhook/[a-z_-]+',
    'payment/[a-z_-]+',
    'app/v1/api/[a-z_-]+',
    'app/v1/chat_api/[a-z_-]+',
    'seller/app/v1/api/[a-z_-]+',
    'seller/app/v1/chat_api/[a-z_-]+',
    'admin/app/v1/api/[a-z_-]+',
    'delivery_boy/app/v1/api/[a-z_-]+',
    'admin/media/upload',
);

/*
|--------------------------------------------------------------------------
| Output Compression
|--------------------------------------------------------------------------
|
| Enables Gzip output compression for faster page loads.  When enabled,
| the output class will test whether your server supports Gzip.
| Even if it does, however, not all browsers support compression
| so enable only if you are reasonably sure your visitors can handle it.
|
| Only used if zlib.output_compression is turned off in your php.ini.
| Please do not use it together with httpd-level output compression.
|
| VERY IMPORTANT:  If you are getting a blank page when compression is enabled it
| means you are prematurely outputting something to your browser. It could
| even be a line of whitespace at the end of one of your scripts.  For
| compression to work, nothing can be sent before the output buffer is called
| by the output class.  Do not 'echo' any values with compression enabled.
|
*/
$config['compress_output'] = FALSE;

/*
|--------------------------------------------------------------------------
| Master Time Reference
|--------------------------------------------------------------------------
|
| Options are 'local' or any PHP supported timezone. This preference tells
| the system whether to use your server's local time as the master 'now'
| reference, or convert it to the configured one timezone. See the 'date
| helper' page of the user guide for information regarding date handling.
|
*/
$config['time_reference'] = 'local';

/*
|--------------------------------------------------------------------------
| Rewrite PHP Short Tags
|--------------------------------------------------------------------------
|
| If your PHP installation does not have short tag support enabled CI
| can rewrite the tags on-the-fly, enabling you to utilize that syntax
| in your view files.  Options are TRUE or FALSE (boolean)
|
| Note: You need to have eval() enabled for this to work.
|
*/
$config['rewrite_short_tags'] = FALSE;

/*
|--------------------------------------------------------------------------
| Reverse Proxy IPs
|--------------------------------------------------------------------------
|
| If your server is behind a reverse proxy, you must whitelist the proxy
| IP addresses from which CodeIgniter should trust headers such as
| HTTP_X_FORWARDED_FOR and HTTP_CLIENT_IP in order to properly identify
| the visitor's IP address.
|
| You can use both an array or a comma-separated list of proxy addresses,
| as well as specifying whole subnets. Here are a few examples:
|
| Comma-separated:	'10.0.1.200,192.168.5.0/24'
| Array:		array('10.0.1.200', '192.168.5.0/24')
*/
$config['proxy_ips'] = '';


/*
|--------------------------------------------------------------------------
| System Modules
|--------------------------------------------------------------------------
| Caution: Deletion of this array can lead to large authorization conflict.
| This is a general array of permissions which are used for user authorization.
| You can use an array for setting up the permissions.
| Here are a few examples:
| 'orders' =>  array('create', 'read', 'update', 'delete'),
| 'attribute' =>  array('create','update', 'delete'),
| 'attribute' =>  array('create', 'delete'),
| In above example ,
| Order is the name of module which is refered as key and the values associated with it are the permissions.

*/

$config['system_modules'] = [
    'orders' =>  array('read', 'update', 'delete'),
    'categories' =>  array('create', 'read', 'update', 'delete'),
    'product' => array('create', 'read', 'update', 'delete'),
    'media' => array('create', 'read', 'update', 'delete'),
    'product_order' => array('read', 'update'),
    'tax' => array('create', 'read', 'update', 'delete'),
    'attribute' => array('create', 'read', 'update', 'delete'),
    'attribute_set' => array('create', 'read', 'update', 'delete'),
    'attribute_value' => array('create', 'read', 'update', 'delete'),
    'home_slider_images' => array('create', 'read', 'update', 'delete'),
    'new_offer_images' => array('create', 'read', 'delete'),
    'promo_code' => array('create', 'read', 'update', 'delete'),
    'featured_section' => array('create', 'read', 'update', 'delete'),
    'customers' => array('read', 'update'),
    'return_request' => array('read', 'update'),
    'delivery_boy' => array('create', 'read', 'update', 'delete'),
    'fund_transfer' => array('create', 'read', 'update', 'delete'),
    'send_notification' => array('create', 'read', 'delete'),
    'notification_setting' => array('read', 'update'),
    'area' => array('create', 'read', 'update', 'delete'),
    'city' => array('create', 'read', 'update', 'delete'),
    'faq' => array('create', 'read', 'update', 'delete'),
    'chat' => array('create', 'read', 'delete')
];

/*
|--------------------------------------------------------------------------
| Media Types
|--------------------------------------------------------------------------
| This is a general array of media types which will help to decide the format/type of document.
| You can use an array for setting up the permissions.
| Here are a few examples:
| 'image' => ['jpg', 'jpeg', 'png','gif','bmp','eps'],
| 'spreadsheet' => ['xls','xsls'],
| In above example ,
| image is the name of format type which is refered as key and the values associated with it are the extension.

*/

$config['type'] = array(
    'image' => ['jpg', 'jpeg', 'png', 'gif', 'bmp', 'eps'],
    'video' => ['mp4', '3gp', 'avchd', 'avi', 'flv', 'mkv', 'mov', 'webm', 'wmv', 'mpg', 'mpeg', 'ogg'],
    'document' => ['doc', 'docx', 'txt', 'pdf', 'ppt', 'pptx'],
    'spreadsheet' => ['xls', 'xsls'],
    'archive' => ['zip', '7z', 'bz2', 'gz', 'gzip', 'rar', 'tar'],
);
